WIP trash maybe?
liqd/liqd-site pull request #79
Opened 2022-08-23 16:52 UTC by phillimorland

2022-08-24 14:57 UTC, phillimorland commented on apps/academy/blocks.py
> -
was un-used

2022-08-25 07:06 UTC, fuzzylogic2000 requested changes
Looks great! But I think we can remove the column count?

2022-08-25 07:06 UTC, fuzzylogic2000 commented on apps/academy/blocks.py
> +    columns_count = ChoiceBlock(choices=[
We don't need the columns count, right?

2022-08-25 07:15 UTC, phillimorland commented on apps/academy/blocks.py
> +        'background and white writing'
not in the meta class just in the block, at least that's how we do it in other files but you're python person so we can change it if you prefer? got it from here https://github.com/liqd/liqd-site/blob/1e9fddaac3c773f49e05526e155cc24aec9d890e/apps/core/blocks.py#L15

2022-08-25 07:17 UTC, phillimorland commented on apps/academy/templates/academy/blocks/block_col_cta.html
> +            {% if forloop.counter == 2 %}
cool as column count was not working :)

2022-08-25 08:15 UTC, fuzzylogic2000 commented on apps/academy/blocks.py
> +        required=False, max_length=28, label='Link Text'
I am so sorry, that I only catched that this time and not with the first time of redoing the migrations, but the link_text needs to be required.

2022-08-25 08:17 UTC, fuzzylogic2000 approved these changes
Nice!

2022-08-25 08:17 UTC, fuzzylogic2000 commented on apps/academy/blocks.py
> +        required=False, max_length=28, label='Link Text'
Or do we also want to be able to use it without link? I guess, yes! :sweat_smile:

2022-08-25 08:19 UTC, merged